spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8



server:
  port: 8083
  tomcat:
    max-http-post-size: 100MB


logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  ERROR