litemall:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wxa5b486c6b918ecfb
    app-secret: e04004829d4c383b4db7769d88dfbca1
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx

  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: false
      host: smtp.qq.com
      username: 2861322722@qq.com
      password: kiowmgjygqrfdchb
      sendfrom: 2861322722@qq.com
      sendto: 2861322722@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      appid: 111111111
      appkey: xxxxxxxxxxxxxx
      template:
      - name: paySucceed
        templateId: 156349
      - name: captcha
        templateId: 156433
      - name: ship
        templateId: 158002
      - name: refund
        templateId: 159447
#    sns:
#      enable: false
#      region: us-west-2
#      accessKey: 469609452868
#      secretKey: lumiere
    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: false
      template:
      - name: paySucceed
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: captcha
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: ship
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: refund
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    jpush:
      enable: true
      secret: 2ab32f908461f85f4768a6e0
      appKey: 745a33482afc15780c161628
      #推送的apns环境，false表示开发，true表示生产；对android和自定义消息无意义
      apnsProduction: false


  # 快鸟物流查询配置
  express:
    enable: false
    appId: "XXXXXXXXX"
    appKey: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    vendors:
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "DBL"
      name: "德邦快递"
    - code: "FAST"
      name: "快捷快递"
    - code: "ZJS"
      name: "宅急送"
    - code: "TNT"
      name: "TNT快递"
    - code: "UPS"
      name: "UPS"
    - code: "DHL"
      name: "DHL"
    - code: "FEDEX"
      name: "FEDEX联邦(国内件)"
    - code: "FEDEX_GJ"
      name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
#      address: http://localhost:8080/wx/storage/fetch/
      address: http://192.168.0.100:8080/wx/storage/fetch/
#      address: http://3.17.10.54/app/wx/storage/fetch/
#      address: http://test.lumierecafe.com/app/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: litemall
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: litemall
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall
  paypal:
    active: true
    #sandbox/live
    mode: sandbox
    client:
      #sandbox
      app: AeiR5dIbE1oYoiRl9cfUSigkoWqBjXjdzR2cCUQgplZDGIipof2-IpwLC06EVPkq0GpLc6swIPfMvmrw
      secret: EIW7Wl0dBpAFU1MBFmwNzaKtU1VVjVD0hh_q2b6XLSt69CGyJWz8UFoJ3J9M716ecxj6KG-N-VsVmkL5
      #live
      #app: Aaqt5dKq4GHNKIuCHL4OWLUXFkCYVlCYJSVEsMP4ZcPsNkTOUNZ6Qdb1N2ULeHj3Riu8gQtVpU3io9YX
      #secret: EDg84jMvetcZm-Ae1NCPxR6kK0IlDk_AQM_0QeWqA6EB5K7Z02P-cGgHOEspo7Q9VPkWiYLUXBYJFfVD
    callback:
      success: http://3.17.10.54/app/wx/paypal/success
      cancel: http://3.17.10.54/app/wx/paypal/calcel
  i18n:
    enable: true
    classes:
        "org.linlinjava.litemall.db.domain.LitemallShop": name,streetAddress
        "org.linlinjava.litemall.db.domain.LitemallGoods": name
        "org.linlinjava.litemall.db.domain.LitemallCategory": name
        "org.linlinjava.litemall.db.domain.LitemallMerchandise": name

  aws:
    enable: true
    appId: 188c7f6b950a4ab49c8760cdb7e5a781
    region: us-west-2
    accessKey: AKIAW2VXHSVCJYXUONED
    secretKey: 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
    originationNumber: Lumiere
    email:
      enable: true
      template:
        captcha: 欢迎注册Lumiere。你的注册码为%s,有效时间一分钟。
        ship: 您的订单已经发货，编号%s，送货人%s ，请注意查收。
    sms:
      enable: true
      template:
        captcha: 欢迎注册Lumiere。你的注册码为%s,有效时间一分钟。