package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShopAdmin;
import org.linlinjava.litemall.db.domain.LitemallShopAdminExample;

public interface LitemallShopAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    long countByExample(LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int insert(LitemallShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    LitemallShopAdmin selectOneByExample(LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    LitemallShopAdmin selectOneByExampleSelective(@Param("example") LitemallShopAdminExample example, @Param("selective") LitemallShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    List<LitemallShopAdmin> selectByExampleSelective(@Param("example") LitemallShopAdminExample example, @Param("selective") LitemallShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    List<LitemallShopAdmin> selectByExample(LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    LitemallShopAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    LitemallShopAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    LitemallShopAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShopAdmin record, @Param("example") LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShopAdmin record, @Param("example") LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}