package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderRecord;
import org.linlinjava.litemall.db.domain.LitemallOrderRecordExample;

public interface LitemallOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int insert(LitemallOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    LitemallOrderRecord selectOneByExample(LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    LitemallOrderRecord selectOneByExampleSelective(@Param("example") LitemallOrderRecordExample example, @Param("selective") LitemallOrderRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    List<LitemallOrderRecord> selectByExampleSelective(@Param("example") LitemallOrderRecordExample example, @Param("selective") LitemallOrderRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    List<LitemallOrderRecord> selectByExample(LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    LitemallOrderRecord selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallOrderRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    LitemallOrderRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    LitemallOrderRecord selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderRecord record, @Param("example") LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderRecord record, @Param("example") LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_record
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}