package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsTax;
import org.linlinjava.litemall.db.domain.LitemallGoodsTaxExample;

public interface LitemallGoodsTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    LitemallGoodsTax selectOneByExample(LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    LitemallGoodsTax selectOneByExampleSelective(@Param("example") LitemallGoodsTaxExample example, @Param("selective") LitemallGoodsTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    List<LitemallGoodsTax> selectByExampleSelective(@Param("example") LitemallGoodsTaxExample example, @Param("selective") LitemallGoodsTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    List<LitemallGoodsTax> selectByExample(LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    LitemallGoodsTax selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    LitemallGoodsTax selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    LitemallGoodsTax selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsTax record, @Param("example") LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsTax record, @Param("example") LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_tax
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}