package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderTax;
import org.linlinjava.litemall.db.domain.LitemallOrderTaxExample;

public interface LitemallOrderTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int insert(LitemallOrderTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    LitemallOrderTax selectOneByExample(LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    LitemallOrderTax selectOneByExampleSelective(@Param("example") LitemallOrderTaxExample example, @Param("selective") LitemallOrderTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    List<LitemallOrderTax> selectByExampleSelective(@Param("example") LitemallOrderTaxExample example, @Param("selective") LitemallOrderTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    List<LitemallOrderTax> selectByExample(LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    LitemallOrderTax selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallOrderTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    LitemallOrderTax selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    LitemallOrderTax selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderTax record, @Param("example") LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderTax record, @Param("example") LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallOrderTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_tax
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}