package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSubscribeGoods;
import org.linlinjava.litemall.db.domain.LitemallSubscribeGoodsExample;

public interface LitemallSubscribeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    long countByExample(LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int insert(LitemallSubscribeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSubscribeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    LitemallSubscribeGoods selectOneByExample(LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    LitemallSubscribeGoods selectOneByExampleSelective(@Param("example") LitemallSubscribeGoodsExample example, @Param("selective") LitemallSubscribeGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    List<LitemallSubscribeGoods> selectByExampleSelective(@Param("example") LitemallSubscribeGoodsExample example, @Param("selective") LitemallSubscribeGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    List<LitemallSubscribeGoods> selectByExample(LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    LitemallSubscribeGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSubscribeGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    LitemallSubscribeGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    LitemallSubscribeGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSubscribeGoods record, @Param("example") LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSubscribeGoods record, @Param("example") LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSubscribeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSubscribeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSubscribeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}