package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsLog;
import org.linlinjava.litemall.db.domain.LitemallGoodsLogExample;

public interface LitemallGoodsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    LitemallGoodsLog selectOneByExample(LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    LitemallGoodsLog selectOneByExampleSelective(@Param("example") LitemallGoodsLogExample example, @Param("selective") LitemallGoodsLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    List<LitemallGoodsLog> selectByExampleSelective(@Param("example") LitemallGoodsLogExample example, @Param("selective") LitemallGoodsLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    List<LitemallGoodsLog> selectByExample(LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    LitemallGoodsLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    LitemallGoodsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    LitemallGoodsLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsLog record, @Param("example") LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsLog record, @Param("example") LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}