package org.linlinjava.litemall.db.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShopGoods;
import org.linlinjava.litemall.db.domain.LitemallShopGoodsExample;

public interface LitemallShopGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    long countByExample(LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int insert(LitemallShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    LitemallShopGoods selectOneByExample(LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    LitemallShopGoods selectOneByExampleSelective(@Param("example") LitemallShopGoodsExample example, @Param("selective") LitemallShopGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    List<LitemallShopGoods> selectByExampleSelective(@Param("example") LitemallShopGoodsExample example, @Param("selective") LitemallShopGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    List<LitemallShopGoods> selectByExample(LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    LitemallShopGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShopGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    LitemallShopGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    LitemallShopGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShopGoods record, @Param("example") LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShopGoods record, @Param("example") LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * 门店商品列表
     */
    List<Map<String, Object>> selectShopGoodsList(@Param("example") Map<String, Object> map, @Param("selective") LitemallShopGoods.Column ... selective);
}