package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsMaxMinusPrice;
import org.linlinjava.litemall.db.domain.LitemallGoodsMaxMinusPriceExample;

public interface LitemallGoodsMaxMinusPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsMaxMinusPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsMaxMinusPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    LitemallGoodsMaxMinusPrice selectOneByExample(LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    LitemallGoodsMaxMinusPrice selectOneByExampleSelective(@Param("example") LitemallGoodsMaxMinusPriceExample example, @Param("selective") LitemallGoodsMaxMinusPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    List<LitemallGoodsMaxMinusPrice> selectByExampleSelective(@Param("example") LitemallGoodsMaxMinusPriceExample example, @Param("selective") LitemallGoodsMaxMinusPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    List<LitemallGoodsMaxMinusPrice> selectByExample(LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    LitemallGoodsMaxMinusPrice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsMaxMinusPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    LitemallGoodsMaxMinusPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    LitemallGoodsMaxMinusPrice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsMaxMinusPrice record, @Param("example") LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsMaxMinusPrice record, @Param("example") LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsMaxMinusPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsMaxMinusPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsMaxMinusPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_max_minus_price
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}