package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMessageReceiver;
import org.linlinjava.litemall.db.domain.LitemallMessageReceiverExample;

public interface LitemallMessageReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    long countByExample(LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int insert(LitemallMessageReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMessageReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    LitemallMessageReceiver selectOneByExample(LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    LitemallMessageReceiver selectOneByExampleSelective(@Param("example") LitemallMessageReceiverExample example, @Param("selective") LitemallMessageReceiver.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    List<LitemallMessageReceiver> selectByExampleSelective(@Param("example") LitemallMessageReceiverExample example, @Param("selective") LitemallMessageReceiver.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    List<LitemallMessageReceiver> selectByExample(LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    LitemallMessageReceiver selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMessageReceiver.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    LitemallMessageReceiver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    LitemallMessageReceiver selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMessageReceiver record, @Param("example") LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMessageReceiver record, @Param("example") LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMessageReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMessageReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallMessageReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_message_receiver
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}