package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCartGoodsAccessory;
import org.linlinjava.litemall.db.domain.LitemallCartGoodsAccessoryExample;

public interface LitemallCartGoodsAccessoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    long countByExample(LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int insert(LitemallCartGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCartGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    LitemallCartGoodsAccessory selectOneByExample(LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    LitemallCartGoodsAccessory selectOneByExampleSelective(@Param("example") LitemallCartGoodsAccessoryExample example, @Param("selective") LitemallCartGoodsAccessory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    List<LitemallCartGoodsAccessory> selectByExampleSelective(@Param("example") LitemallCartGoodsAccessoryExample example, @Param("selective") LitemallCartGoodsAccessory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    List<LitemallCartGoodsAccessory> selectByExample(LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    LitemallCartGoodsAccessory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCartGoodsAccessory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    LitemallCartGoodsAccessory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    LitemallCartGoodsAccessory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCartGoodsAccessory record, @Param("example") LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCartGoodsAccessory record, @Param("example") LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCartGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCartGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallCartGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cart_goods_accessory
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}