package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSubscribeShop;
import org.linlinjava.litemall.db.domain.LitemallSubscribeShopExample;

public interface LitemallSubscribeShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    long countByExample(LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int insert(LitemallSubscribeShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSubscribeShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    LitemallSubscribeShop selectOneByExample(LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    LitemallSubscribeShop selectOneByExampleSelective(@Param("example") LitemallSubscribeShopExample example, @Param("selective") LitemallSubscribeShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    List<LitemallSubscribeShop> selectByExampleSelective(@Param("example") LitemallSubscribeShopExample example, @Param("selective") LitemallSubscribeShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    List<LitemallSubscribeShop> selectByExample(LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    LitemallSubscribeShop selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSubscribeShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    LitemallSubscribeShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    LitemallSubscribeShop selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSubscribeShop record, @Param("example") LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSubscribeShop record, @Param("example") LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSubscribeShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSubscribeShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSubscribeShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_subscribe_shop
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}