package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserRechargeOrder;
import org.linlinjava.litemall.db.domain.LitemallUserRechargeOrderExample;

public interface LitemallUserRechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int insert(LitemallUserRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    LitemallUserRechargeOrder selectOneByExample(LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    LitemallUserRechargeOrder selectOneByExampleSelective(@Param("example") LitemallUserRechargeOrderExample example, @Param("selective") LitemallUserRechargeOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    List<LitemallUserRechargeOrder> selectByExampleSelective(@Param("example") LitemallUserRechargeOrderExample example, @Param("selective") LitemallUserRechargeOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    List<LitemallUserRechargeOrder> selectByExample(LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    LitemallUserRechargeOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserRechargeOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    LitemallUserRechargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    LitemallUserRechargeOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserRechargeOrder record, @Param("example") LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserRechargeOrder record, @Param("example") LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_recharge_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}