package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShopMerchandise;
import org.linlinjava.litemall.db.domain.LitemallShopMerchandiseExample;

public interface LitemallShopMerchandiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    long countByExample(LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int insert(LitemallShopMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShopMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    LitemallShopMerchandise selectOneByExample(LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    LitemallShopMerchandise selectOneByExampleSelective(@Param("example") LitemallShopMerchandiseExample example, @Param("selective") LitemallShopMerchandise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    List<LitemallShopMerchandise> selectByExampleSelective(@Param("example") LitemallShopMerchandiseExample example, @Param("selective") LitemallShopMerchandise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    List<LitemallShopMerchandise> selectByExample(LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    LitemallShopMerchandise selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShopMerchandise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    LitemallShopMerchandise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    LitemallShopMerchandise selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShopMerchandise record, @Param("example") LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShopMerchandise record, @Param("example") LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShopMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShopMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallShopMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_merchandise
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}