package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShopLog;
import org.linlinjava.litemall.db.domain.LitemallShopLogExample;

public interface LitemallShopLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int insert(LitemallShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    LitemallShopLog selectOneByExample(LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    LitemallShopLog selectOneByExampleSelective(@Param("example") LitemallShopLogExample example, @Param("selective") LitemallShopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    List<LitemallShopLog> selectByExampleSelective(@Param("example") LitemallShopLogExample example, @Param("selective") LitemallShopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    List<LitemallShopLog> selectByExample(LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    LitemallShopLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    LitemallShopLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    LitemallShopLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShopLog record, @Param("example") LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShopLog record, @Param("example") LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}