package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsProductLog;
import org.linlinjava.litemall.db.domain.LitemallGoodsProductLogExample;

public interface LitemallGoodsProductLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    LitemallGoodsProductLog selectOneByExample(LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    LitemallGoodsProductLog selectOneByExampleSelective(@Param("example") LitemallGoodsProductLogExample example, @Param("selective") LitemallGoodsProductLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    List<LitemallGoodsProductLog> selectByExampleSelective(@Param("example") LitemallGoodsProductLogExample example, @Param("selective") LitemallGoodsProductLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    List<LitemallGoodsProductLog> selectByExample(LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    LitemallGoodsProductLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsProductLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    LitemallGoodsProductLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    LitemallGoodsProductLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsProductLog record, @Param("example") LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsProductLog record, @Param("example") LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}