package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderGoodsAccessory;
import org.linlinjava.litemall.db.domain.LitemallOrderGoodsAccessoryExample;

public interface LitemallOrderGoodsAccessoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int insert(LitemallOrderGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    LitemallOrderGoodsAccessory selectOneByExample(LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    LitemallOrderGoodsAccessory selectOneByExampleSelective(@Param("example") LitemallOrderGoodsAccessoryExample example, @Param("selective") LitemallOrderGoodsAccessory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    List<LitemallOrderGoodsAccessory> selectByExampleSelective(@Param("example") LitemallOrderGoodsAccessoryExample example, @Param("selective") LitemallOrderGoodsAccessory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    List<LitemallOrderGoodsAccessory> selectByExample(LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    LitemallOrderGoodsAccessory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallOrderGoodsAccessory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    LitemallOrderGoodsAccessory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    LitemallOrderGoodsAccessory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderGoodsAccessory record, @Param("example") LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderGoodsAccessory record, @Param("example") LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderGoodsAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallOrderGoodsAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods_accessory
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}