package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGiftCardOrder;
import org.linlinjava.litemall.db.domain.LitemallGiftCardOrderExample;

public interface LitemallGiftCardOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int insert(LitemallGiftCardOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGiftCardOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    LitemallGiftCardOrder selectOneByExample(LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    LitemallGiftCardOrder selectOneByExampleSelective(@Param("example") LitemallGiftCardOrderExample example, @Param("selective") LitemallGiftCardOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    List<LitemallGiftCardOrder> selectByExampleSelective(@Param("example") LitemallGiftCardOrderExample example, @Param("selective") LitemallGiftCardOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    List<LitemallGiftCardOrder> selectByExample(LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    LitemallGiftCardOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGiftCardOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    LitemallGiftCardOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    LitemallGiftCardOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGiftCardOrder record, @Param("example") LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGiftCardOrder record, @Param("example") LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGiftCardOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGiftCardOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGiftCardOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_gift_card_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}