package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSettlementLog;
import org.linlinjava.litemall.db.domain.LitemallSettlementLogExample;

public interface LitemallSettlementLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    long countByExample(LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int insert(LitemallSettlementLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSettlementLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    LitemallSettlementLog selectOneByExample(LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    LitemallSettlementLog selectOneByExampleSelective(@Param("example") LitemallSettlementLogExample example, @Param("selective") LitemallSettlementLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    List<LitemallSettlementLog> selectByExampleSelective(@Param("example") LitemallSettlementLogExample example, @Param("selective") LitemallSettlementLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    List<LitemallSettlementLog> selectByExample(LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    LitemallSettlementLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSettlementLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    LitemallSettlementLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    LitemallSettlementLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSettlementLog record, @Param("example") LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSettlementLog record, @Param("example") LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSettlementLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSettlementLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSettlementLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_settlement_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}