package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMerchandise;
import org.linlinjava.litemall.db.domain.LitemallMerchandiseExample;

public interface LitemallMerchandiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    long countByExample(LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int insert(LitemallMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    LitemallMerchandise selectOneByExample(LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    LitemallMerchandise selectOneByExampleSelective(@Param("example") LitemallMerchandiseExample example, @Param("selective") LitemallMerchandise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    List<LitemallMerchandise> selectByExampleSelective(@Param("example") LitemallMerchandiseExample example, @Param("selective") LitemallMerchandise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    List<LitemallMerchandise> selectByExample(LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    LitemallMerchandise selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMerchandise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    LitemallMerchandise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    LitemallMerchandise selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMerchandise record, @Param("example") LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMerchandise record, @Param("example") LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMerchandise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallMerchandiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchandise
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}