package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTax;
import org.linlinjava.litemall.db.domain.LitemallTaxExample;

public interface LitemallTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    long countByExample(LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int insert(LitemallTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    LitemallTax selectOneByExample(LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    LitemallTax selectOneByExampleSelective(@Param("example") LitemallTaxExample example, @Param("selective") LitemallTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    List<LitemallTax> selectByExampleSelective(@Param("example") LitemallTaxExample example, @Param("selective") LitemallTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    List<LitemallTax> selectByExample(LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    LitemallTax selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTax.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    LitemallTax selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    LitemallTax selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTax record, @Param("example") LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTax record, @Param("example") LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tax
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}