package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallI18n;
import org.linlinjava.litemall.db.domain.LitemallI18nExample;

public interface LitemallI18nMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    long countByExample(LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int insert(LitemallI18n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int insertSelective(LitemallI18n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    LitemallI18n selectOneByExample(LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    LitemallI18n selectOneByExampleSelective(@Param("example") LitemallI18nExample example, @Param("selective") LitemallI18n.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    List<LitemallI18n> selectByExampleSelective(@Param("example") LitemallI18nExample example, @Param("selective") LitemallI18n.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    List<LitemallI18n> selectByExample(LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    LitemallI18n selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallI18n.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    LitemallI18n selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    LitemallI18n selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallI18n record, @Param("example") LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallI18n record, @Param("example") LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallI18n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallI18n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_i18n
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}