package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallAdminOrderMerchandise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.admin_order_id
     *
     * @mbg.generated
     */
    private Integer adminOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.merchandise_id
     *
     * @mbg.generated
     */
    private Integer merchandiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.merchandise_name
     *
     * @mbg.generated
     */
    private String merchandiseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.merchandise_sn
     *
     * @mbg.generated
     */
    private String merchandiseSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.comment
     *
     * @mbg.generated
     */
    private Integer comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_admin_order_merchandise.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.id
     *
     * @return the value of litemall_admin_order_merchandise.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.id
     *
     * @param id the value for litemall_admin_order_merchandise.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.admin_order_id
     *
     * @return the value of litemall_admin_order_merchandise.admin_order_id
     *
     * @mbg.generated
     */
    public Integer getAdminOrderId() {
        return adminOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.admin_order_id
     *
     * @param adminOrderId the value for litemall_admin_order_merchandise.admin_order_id
     *
     * @mbg.generated
     */
    public void setAdminOrderId(Integer adminOrderId) {
        this.adminOrderId = adminOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.merchandise_id
     *
     * @return the value of litemall_admin_order_merchandise.merchandise_id
     *
     * @mbg.generated
     */
    public Integer getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.merchandise_id
     *
     * @param merchandiseId the value for litemall_admin_order_merchandise.merchandise_id
     *
     * @mbg.generated
     */
    public void setMerchandiseId(Integer merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.merchandise_name
     *
     * @return the value of litemall_admin_order_merchandise.merchandise_name
     *
     * @mbg.generated
     */
    public String getMerchandiseName() {
        return merchandiseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.merchandise_name
     *
     * @param merchandiseName the value for litemall_admin_order_merchandise.merchandise_name
     *
     * @mbg.generated
     */
    public void setMerchandiseName(String merchandiseName) {
        this.merchandiseName = merchandiseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.merchandise_sn
     *
     * @return the value of litemall_admin_order_merchandise.merchandise_sn
     *
     * @mbg.generated
     */
    public String getMerchandiseSn() {
        return merchandiseSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.merchandise_sn
     *
     * @param merchandiseSn the value for litemall_admin_order_merchandise.merchandise_sn
     *
     * @mbg.generated
     */
    public void setMerchandiseSn(String merchandiseSn) {
        this.merchandiseSn = merchandiseSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.number
     *
     * @return the value of litemall_admin_order_merchandise.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.number
     *
     * @param number the value for litemall_admin_order_merchandise.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.price
     *
     * @return the value of litemall_admin_order_merchandise.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.price
     *
     * @param price the value for litemall_admin_order_merchandise.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.pic_url
     *
     * @return the value of litemall_admin_order_merchandise.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.pic_url
     *
     * @param picUrl the value for litemall_admin_order_merchandise.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.comment
     *
     * @return the value of litemall_admin_order_merchandise.comment
     *
     * @mbg.generated
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.comment
     *
     * @param comment the value for litemall_admin_order_merchandise.comment
     *
     * @mbg.generated
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.add_time
     *
     * @return the value of litemall_admin_order_merchandise.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.add_time
     *
     * @param addTime the value for litemall_admin_order_merchandise.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.update_time
     *
     * @return the value of litemall_admin_order_merchandise.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.update_time
     *
     * @param updateTime the value for litemall_admin_order_merchandise.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_admin_order_merchandise.deleted
     *
     * @return the value of litemall_admin_order_merchandise.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_admin_order_merchandise.deleted
     *
     * @param deleted the value for litemall_admin_order_merchandise.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", adminOrderId=").append(adminOrderId);
        sb.append(", merchandiseId=").append(merchandiseId);
        sb.append(", merchandiseName=").append(merchandiseName);
        sb.append(", merchandiseSn=").append(merchandiseSn);
        sb.append(", number=").append(number);
        sb.append(", price=").append(price);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", comment=").append(comment);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallAdminOrderMerchandise other = (LitemallAdminOrderMerchandise) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAdminOrderId() == null ? other.getAdminOrderId() == null : this.getAdminOrderId().equals(other.getAdminOrderId()))
            && (this.getMerchandiseId() == null ? other.getMerchandiseId() == null : this.getMerchandiseId().equals(other.getMerchandiseId()))
            && (this.getMerchandiseName() == null ? other.getMerchandiseName() == null : this.getMerchandiseName().equals(other.getMerchandiseName()))
            && (this.getMerchandiseSn() == null ? other.getMerchandiseSn() == null : this.getMerchandiseSn().equals(other.getMerchandiseSn()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getPicUrl() == null ? other.getPicUrl() == null : this.getPicUrl().equals(other.getPicUrl()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAdminOrderId() == null) ? 0 : getAdminOrderId().hashCode());
        result = prime * result + ((getMerchandiseId() == null) ? 0 : getMerchandiseId().hashCode());
        result = prime * result + ((getMerchandiseName() == null) ? 0 : getMerchandiseName().hashCode());
        result = prime * result + ((getMerchandiseSn() == null) ? 0 : getMerchandiseSn().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPicUrl() == null) ? 0 : getPicUrl().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_admin_order_merchandise
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        adminOrderId("admin_order_id", "adminOrderId", "INTEGER", false),
        merchandiseId("merchandise_id", "merchandiseId", "INTEGER", false),
        merchandiseName("merchandise_name", "merchandiseName", "VARCHAR", false),
        merchandiseSn("merchandise_sn", "merchandiseSn", "VARCHAR", false),
        number("number", "number", "INTEGER", true),
        price("price", "price", "DECIMAL", false),
        picUrl("pic_url", "picUrl", "VARCHAR", false),
        comment("comment", "comment", "INTEGER", true),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_admin_order_merchandise
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}