#礼物卡paypal支付回调地址配置
card:
  paypal:
    success: http://192.168.0.100:8080/wx/card/pay/success
    cancel: http://192.168.0.100:8080/wx/card/pay/cancel
#netty消息配置
webSocket:
  netty:
    active: false
    port: 58080
    path: /webSocket

zone:
  offset: 0

barcode:
  key: Yliyun_123